erDiagram

%% Fechas
dim_fecha ||--|{ ft_reclamo_transaccion_ss: 
    "Id_Fecha_Transaccion
    Id_Fecha_Efectiva"

br_grupo_asegurado_d ||--|{ ft_reclamo_transaccion_ss: Id_Asegurado
br_grupo_asegurado_d ||--|{ dim_asegurado_d: Id_A
dim_asegurado_d ||--|{ br_asegurado_clasificacion_d: Id_Asegurado
dim_north_american_industry_classification_w ||--|{ br_asegurado_clasificacion_d: Cod_Naics
dim_standard_industrial_classification_w ||--|{ br_asegurado_clasificacion_d: Cod_Sic
dim_empleado_d ||--|{ ft_reclamo_transaccion_ss: 
    "Id_Empleado
    Id_Agente"
dim_coberturas_d ||--|{ ft_reclamo_transaccion_ss: 
    "Id_Cobertura
    Item_Cobertura"
dim_reclamador_d ||--|{ ft_reclamo_transaccion_ss: Id_Reclamador
%%dim_tipo_reclamo_d ||--|{ ft_reclamo_transaccion_ss: Id_Tipo_Reclamo
dim_reclamo_perfil_w ||--|{ ft_reclamo_transaccion_ss: Id_Perfil_Reclamo
dim_reclamo_d ||--|{ ft_reclamo_transaccion_ss: Id_Reclamo

%% Supertypes and subtypes
link_item_cobertura_ss ||--|| ft_reclamo_transaccion_ss: Id_Item
dim_cobertura_auto_ss ||--|| link_item_cobertura_ss: Id_Item
dim_cobertura_inmu_ss ||--|| link_item_cobertura_ss: Id_Item
dim_cobertura_pers_ss ||--|| link_item_cobertura_ss: Id_Item

%% Fact
ft_reclamo_transaccion_ss {
    string Id_Fecha_Transaccion fk
    string Id_Fecha_Efectiva fk
    string Id_Asegurado fk
    string Id_Empleado fk
    string Id_Agente fk
    string Id_Cobertura fk
    string Item_Cobertura fk
    string Id_Reclamador fk
    string Id_Perfil_Reclamo fk
    string Id_Reclamo fk
    string Id_Poliza
    string Id_Reclamo_Transaccion
    string Id_Reclamo_Transaccion_Dolar
    string Id_Supervisor
    string Status
    string Original_Reserva_Dolar_Monto
    string Estimar_Dolar_Monto
    string Actual_Reserva_Fecha_Dolar_Monto
    string Reclamo_Pagado_Fecha_Dolar_Monto
    string Salvage_Collected_To_Date_Dollar_Amount
    string Subro_Payment_Collected_To_Date_Dollar_Amount
    string Reclamo_Perdida_Hasta_Apertura_Lag
    string Reclamo_Apertura_Hasta_Estimate_Lag
    string Reclamo_Apertura_Hasta_1st_Pago_Lag
    string Reclamo_Apertura_Hasta_Cierre_Lag
    string Numero_Transacciones_Reclamo
}

%% Dimension Role Playing
dim_fecha {
    string Id_Fecha pk
    int Mes
    int Ano
    int Dia
    int Trimestre
    string Dia_Semana
    bool Feriado
}

br_grupo_asegurado_d {
    string Id_Asegurado fk
    string Id_Grupo_Asegurado
}

dim_asegurado_d {
    date Fecha_Edit
    string Id_Asegurado pk
    string Nombre_Completo
    string Fecha_Nacimiento 
    string Genero
    int Cod_Postal
    string Desc_Segmento_Hist
    string Desc_Segmento
    string Estado_Civil
}

%% Bridge
br_asegurado_clasificacion_d {
    string Id_Asegurado fk
    string Naics_Code fk
    string Sic_Code fk
}

dim_north_american_industry_classification_w {
    string Cod_Naics pk
    string Desc_Naics
}

dim_standard_industrial_classification_w {
    string Cod_Sic pk
    string Desc_Sic
}

dim_empleado_d {
    string Id_Empleado pk
    string Nombre
    string Region
    string Tipo
    %% Agente o no agente
}

dim_reclamo_perfil_w {
    string Id_Perfil_Reclamo pk
    string Metodo_Reporte
    string Es_Catastrofico
    string Tipo_Perdida
    string Zona_Perdida
}

dim_reclamador_d {
    string Id_Reclamador pk
    string Nombre
    string Direccion
    string Ciudad
    string Estado
    string Codigo_Postal
    string Telefono
    string Tipo
}

%% SUPERTYPES AND SUBTYPES

%% SUPERTYPE
link_item_cobertura_ss {
    string Id_Item pk
    string Linea_De_Negocio
}

%% SUBTYPE
dim_cobertura_auto_ss {
    string Id_Item pk
    string Id_Cobertura fk
    string Desc_Marca
    int Ano_Fabricacion
    string Desc_Clasificacion
}

%% SUBTYPE
dim_cobertura_inmu_ss {
    string Id_Item pk
    string Id_Cobertura fk
    int Metros_Cuadrados
    date Fecha_Construccion
    string Cod_Postal
}

%% SUBTYPE
dim_cobertura_pers_ss {
    string Id_Item pk
    string Id_Cobertura fk
    string Desc_Item
}

%% Coverages descriptiva
dim_coberturas_d {
    string Id_Cobertura pk
    string Descripcion
    string Tipo_Cobertura
    string Categoria
    float Limite
    float Deducible
}

dim_reclamo_d {
    string Id_Reclamo pk
    string Numero_Reclamo
    string Estado_Reclamo
    string Descripcion_Reclamo
}