erDiagram

%% Fact
ft_policy_claim_transaccion_ss {
    %% falta la dimension de month end
    string Id_Mes
    string Id_Asegurado fk
    string Id_Agente fk
    string Id_Cobertura fk
    string Item_Cobertura fk
    string Id_Poliza
    string Status_Poliza
    string written_premium_revenue_amount
    string Ganancia_premium_Escrita_monto
    string Adquirida_premium_Ganancia_monto
}


%% Dimension Role Playing
dim_Mes {
    string Id_Fecha pk
    int Mes
}



br_Grupo_Asegurado_d {
    string Id_Asegurado fk
    string ID_Grupo_Asegurado
}


dim_Asegurado_d {
    date Fecha_Edit
    string Id_Asegurado pk
    string Nombre_Completo
    string Fecha_Nacimiento 
    string Genero
    int Cod_postal
    string Desc_Segmento_Hist
    string Desc_Segmento
    string Estado_Civil
}

%% Bridge
br_Asegurado_Clasificacion_d {
    string Id_Asegurado fk
    string NAICS_Code fk
    string SIC_Code fk
}

dim_north_american_industry_classification_w {
    string Cod_NAICS pk
    string Desc_NAICS
}

dim_standard_industrial_classification_w {
    string Cod_SIC pk
    string Desc_SIC
}





%% SUPERTYPES AND SUBTYPES

%% SUPERTYPE
link_item_cobertura_ss {
    string Id_Item pk
    string Linea_de_negocio
}

%% SUBTYPE
dim_cobertura_auto_ss {
    string Id_Item pk
    string Id_Cobertura fk
    string Desc_Marca
    int Ano_Fabricacion
    string Desc_clasificacion
}

%% SUBTYPE
dim_cobertura_inmu_ss {
    string Id_Item pk
    string Id_Cobertura fk
    Int Metros_Cuadrados
    date Fecha_Construccion
    string Cod_Postal
}

%% SUBTYPE
dim_cobertura_pers_ss {
    string Id_Item pk
    string Id_Cobertura fk
    string Desc_Item
}



%% Coverages descriptiva
dim_coberturas_d {
    string Id_Covertura pk
    string Descripcion
    string Tipo_Cobertura
    string Categoria
    float Limite
    float Deducible
}



dim_agente {
    string Id_Agente pk
    string Nombre_Agente
    string Region
    string Area_Ventas
}